version: "2"
services:
  postgres:
    image: postgres:9.6
    environment:
      - PGUSER=postgres
      - PGDATABASE=api
      - PGHOST=postgres
    ports:
      - "1215:5432"
  web:
    build: .
    command: bin/rails server --port 3000 --binding 0.0.0.0
    volumes:
      - .:/api
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    links:
      - postgres
volumes:
  bundle:

